### ISSUE TITLE
More use cases

### ISSUE THREAD

**Issue by neves** [spatie/vue-expose-inject#2]
Now that's in Vue 2.2, I would like to know more use cases for this feature.
So far I see use for:

1. EventBus
2. API Dependency Injection for easy testing
3. Global plugins like router, auth, firebase, etc

Any more ideas?

**Comment by sebastiandedeyne** [comment]
I think those are the most common use cases.

The main reason I wanted this feature is for the DI to replace `import` statements that import singleton modules.

**Comment by randallknutson** [comment]
I've got another use case. We are creating something similar to angular providers that define components, views, routes and store in a reusable manner. These each have a set of settings we want to make available within them. While searching for if vue had something similar to react's context I found your module and it appears to do exactly what I was looking for. I can now expose the provider at the provider's root and all child routes/components can then inject the provider instance and use the settings.
